# Generated by Django 3.2.7 on 2021-10-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.CharField(default=0, max_length=5, verbose_name='House'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=0, max_length=11, verbose_name='Phone number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.CharField(default=0, max_length=50, verbose_name='Street'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
