# Generated by Django 3.2.8 on 2021-10-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzausers',
            name='done',
        ),
        migrations.AlterField(
            model_name='pizzausers',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
