# Generated by Django 3.2.7 on 2021-10-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_company', '0003_auto_20211009_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=50, verbose_name='Password'),
            preserve_default=False,
        ),
    ]
