# Generated by Django 3.2.7 on 2021-10-10 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_company', '0004_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.CreateModel(
            name='PizzaUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=5)),
                ('apartment', models.PositiveSmallIntegerField()),
                ('total', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_company.user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_company.pizzausers')),
                ('pizza', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza_company.pizza')),
            ],
            options={
                'verbose_name': 'Information of order',
                'verbose_name_plural': 'Information of orders',
            },
        ),
    ]
