# Generated by Django 3.2.7 on 2021-10-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_company', '0005_auto_20211010_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzausers',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
